<a href="https://colab.research.google.com/github/Jaison0317/Calculador-en-C-.NET/blob/master/AI%20-%20Clase_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import torch
import numpy as np

import pandas as pd

# Trabajando con tensores
---

In [2]:
torch.__version__

'1.6.0+cu101'

In [3]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [11]:
tensor_b = torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[5.7044e-37, 0.0000e+00],
        [5.6052e-45, 0.0000e+00]])


tensor([[0.8846, 0.7517],
        [0.0289, 0.2508]])

In [14]:
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.1689, 0.8976],
        [0.1888, 0.8203]])

In [15]:
result = tensor_b + tensor_c
result

tensor([[1.0535, 1.6494],
        [0.2177, 1.0711]])

In [18]:
result.shape
reshape = result.view(4,1)
reshape

tensor([[1.0535],
        [1.6494],
        [0.2177],
        [1.0711]])

In [23]:
points = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(points)
points[0][1] = 2.5
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [24]:
points, points.stride()

(tensor([[1.0000, 2.5000],
         [3.0000, 4.0000]]), (2, 1))

In [27]:
p_t = points.t()
p_t

tensor([[1.0000, 3.0000],
        [2.5000, 4.0000]])

In [29]:
tensor_x = torch.tensor([1, 2, 3, 4])
#tensor_x, torch.unsqueeze(tensor_x, 0)
tensor_x, torch.unsqueeze(tensor_x, 1)


(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [39]:
numpyArray = np.random.randn(2,2)
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[-0.3448,  0.9373],
        [ 0.5884, -0.3954]], dtype=torch.float64)

# Representar datos con tensores

---



In [46]:
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[-0.3448,  0.9373],
        [ 0.5884, -0.3954]], dtype=torch.float64)
tensor(0.1964, dtype=torch.float64)
tensor([0.1218, 0.2710], dtype=torch.float64)
tensor([0.2962, 0.0965], dtype=torch.float64)


In [51]:
torch.std(from_numpy, dim=1)

tensor([0.9066, 0.6956], dtype=torch.float64)

In [53]:
torch.save(from_numpy, 'tensor.t')

In [70]:
load = torch.load('tensor.t')
load

tensor([[-0.3448,  0.9373],
        [ 0.5884, -0.3954]], dtype=torch.float64)

In [74]:
 url = "Complete/CompleteDataset.csvv"
 dataframe = pd.read_csv(url) #Leer contenido representandolo en filas y columnas
 dataframe

FileNotFoundError: ignored

In [75]:
dataframe.columns

NameError: ignored